dist: xenial
sudo: required

language: bash

env:
  global:
    - PASS_VERSION=1.7.3
    - TOMB_VERSION=2.5
    - KCOV_VERSION=36

addons:
  apt:
    packages:
      - tree
      - zsh
      - gnupg
      - cryptsetup
      - gawk
      - e2fsprogs
      - dcfldd
      - gettext
      - ca-certificates
      - shellcheck
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_script:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - sudo make --directory=password-store-$PASS_VERSION install
  - wget https://github.com/dyne/Tomb/archive/v$TOMB_VERSION.tar.gz
  - tar -xzf v$TOMB_VERSION.tar.gz
  - sudo make --directory=Tomb-$TOMB_VERSION install
  - sudo swapoff -a
  - wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.tar.gz
  - tar xzf v$KCOV_VERSION.tar.gz
  - mkdir kcov-$KCOV_VERSION/build
  - cd kcov-$KCOV_VERSION/build && cmake .. && cd ../..
  - make --directory=kcov-$KCOV_VERSION/build
  - sudo make install --directory=kcov-$KCOV_VERSION/build
  - rm -rf kcov-$KCOV_VERSION

script:
  - make test

notifications:
  email: false
